otoyo/astro-notion-blog

- package.json
- src/lib/blog-helpers.ts
- yarn.lock
https://github.com/otoyo/astro-notion-blog/issues/2 の問題に対応しました。
ローカルで動かす場合はコミット取り込み後 `yarn install` を実行してください。
> Fix blob fetch

- .gitignore
> Ignore .node-version

- src/components/notion-blocks/Bookmark.astro
ref. https://github.com/otoyo/astro-notion-blog/issues/11
> Check metadata existence

- src/pages/blog/tag/[tag]/page/[page].astro
ref. https://github.com/otoyo/astro-notion-blog/issues/14
> Fix generating pagination of tags pages

- src/components/notion-blocks/Heading1.astro
- src/components/notion-blocks/Heading2.astro
- src/components/notion-blocks/Heading3.astro
Fix https://github.com/otoyo/astro-notion-blog/issues/16
> Fix Heading with toggle blocks style

- .gitignore
- .nxignore
- README.ja.md
- README.md
- nx.json
- package.json
- scripts/blog-contents-cache.cjs
- scripts/retrieve-block-children.cjs
- src/lib/notion/client.ts
- yarn.lock
Cache API response with [nx](https://nx.dev/) to speed up build.
* Number of pages: 288
* Time to get API response
* No cache: 1,063s
* Cached(local): 103s
> Cache API response with nx

- package.json
> Remove tmp files on purge

- src/components/NotionBlocks.astro
- src/components/PostFeaturedImage.astro
- src/components/notion-blocks/Image.astro
- src/lib/blog-helpers.ts
> Fetch images concurrently

- src/components/PostFeaturedImage.astro
- src/lib/blog-helpers.ts
- src/pages/blog/index.astro
- src/pages/blog/page/[page].astro
- src/pages/blog/tag/[tag].astro
- src/pages/blog/tag/[tag]/page/[page].astro
> Fetch featured images beforehand

- src/pages/blog/[slug].astro
ref. https://github.com/otoyo/astro-notion-blog/pull/27
> Handle empty tags

- src/components/BlogTagsLink.astro
- src/lib/notion/client.ts
- src/pages/blog/tag/[tag].astro
- src/pages/blog/tag/[tag]/page/[page].astro
> Color tags list

- src/components/BlogPostsLink.astro
- src/components/BlogTagsLink.astro
> Add margin

- package.json
> Ignore dot directories

- src/layouts/Layout.astro
- src/pages/blog/page/[page].astro
- src/pages/blog/tag/[tag].astro
- src/pages/blog/tag/[tag]/page/[page].astro
> Change h2 style

- src/layouts/Layout.astro
ref. https://github.com/otoyo/astro-notion-blog/pull/38
> Set default background color to h2

- src/components/BlogTagsLink.astro
- src/components/PostTags.astro
- src/pages/blog/tag/[tag].astro
- src/pages/blog/tag/[tag]/page/[page].astro
- src/styles/notion-color.css
> Reflect tag color

- .github/workflows/deploy.yml
> Add workflow for deloy

- src/lib/notion/client.ts
- src/pages/feed.ts
> Excerpt in RSS

- scripts/blog-contents-cache.cjs
ref. https://github.com/otoyo/astro-notion-blog/issues/43
> Continue to build

- astro.config.mjs
- package.json
- src/integrations/og-image-uploader.ts
- src/layouts/Layout.astro
- src/lib/cloudinary/client.ts
- src/pages/blog/[slug].astro
- src/server-constants.ts
- yarn.lock
1. Sign up [Cloudinary](https://cloudinary.com/) and sign in
2. Select Node.js and note the value of `cloud_name`, `api_key` and `api_secret`
3. Go to [Cloudflare Pages](https://pages.cloudflare.com/) and open "Environment variables" settings of the production
4. Input the value of `cloud_name` as `CLOUDINARY_CLOUD_NAME`, `api_key` as `CLOUDINARY_API_KEY` and `api_secret` as `CLOUDINARY_API_SECRET`, then save
5. Set the same environment variables to the preview
6. Redeploy
> OG images for each post

- src/lib/notion/client.ts
ref. https://github.com/otoyo/astro-notion-blog/pull/21
> Reload image blocks

- src/components/PostTitle.astro
- src/lib/interfaces.ts
- src/lib/notion/client.ts
- src/lib/notion/responses.ts
> Support page icon

- src/components/notion-blocks/Code.astro
> Copy button

- src/components/notion-blocks/Code.astro
ref. https://github.com/otoyo/astro-notion-blog/pull/52
> Fix Code caption

- src/components/notion-blocks/Code.astro
ref. https://github.com/otoyo/astro-notion-blog/pull/54
> Ignore pre code tags

- src/components/PostRelativeLink.astro
- src/pages/blog/[slug].astro
> Link under post

- src/components/PostRelativeLink.astro
ref. https://github.com/otoyo/astro-notion-blog/pull/57
> Fix relative links

- astro.config.mjs
- src/components/PostRelativeLink.astro
- src/layouts/Layout.astro
- src/lib/blog-helpers.ts
- src/lib/utils.ts
- src/server-constants.ts
> Support subpath

- astro.config.mjs
- src/server-constants.ts
> [Refactoring] Define CUSTOM_DOMAIN in server-constants

- astro.config.mjs
ref. https://github.com/otoyo/astro-notion-blog/pull/59
> Fix astro config

- src/components/notion-blocks/Table.astro
> Remove white-space

- src/components/NotionBlocks.astro
- src/components/PostFeaturedImage.astro
- src/components/notion-blocks/File.astro
- src/components/notion-blocks/Image.astro
- src/lib/blog-helpers.ts
- src/lib/interfaces.ts
- src/lib/notion/client.ts
- src/pages/blog/[slug].astro
Fix https://github.com/otoyo/astro-notion-blog/issues/53
> Support file blocks

- src/components/notion-blocks/Caption.astro
- src/components/notion-blocks/Image.astro
> Fix image block style

- .github/pull.yml
Add config for https://wei.github.io/pull/
> Add pull config

- src/components/notion-blocks/Heading1.astro
- src/components/notion-blocks/Heading2.astro
- src/components/notion-blocks/Heading3.astro
> Fix Heading2 and Headings' children

- src/server-constants.ts
Fix https://github.com/otoyo/astro-notion-blog/issues/71
> Read from import.meta.env first

- src/lib/blog-helpers.ts
- src/server-constants.ts
> Allow YouTube Live URL

- src/components/notion-blocks/Image.astro
Fix. https://github.com/otoyo/astro-notion-blog/issues/84
> Specify data-type as image

- src/layouts/Layout.astro
- src/lib/blog-helpers.ts
Fixes https://github.com/otoyo/astro-notion-blog/issues/83
> Fix script path

- src/integrations/public-notion-copier.ts
Fixes https://github.com/otoyo/astro-notion-blog/issues/82
> Consider file existing

- src/components/notion-blocks/annotations/Anchor.astro
- src/components/notion-blocks/annotations/Bold.astro
- src/components/notion-blocks/annotations/Code.astro
- src/components/notion-blocks/annotations/Color.astro
- src/components/notion-blocks/annotations/Italic.astro
- src/components/notion-blocks/annotations/Strikethrough.astro
- src/components/notion-blocks/annotations/Underline.astro
Fixes https://github.com/otoyo/astro-notion-blog/issues/81
> Remove spaces

- src/components/PostTitle.astro
- src/components/notion-blocks/Callout.astro
- src/lib/interfaces.ts
- src/lib/notion/client.ts
- src/lib/notion/responses.ts
Fixes https://github.com/otoyo/astro-notion-blog/issues/78
> Support icon

- astro.config.mjs
- src/integrations/blog-metadata-setter.ts
- src/layouts/Layout.astro
- src/lib/interfaces.ts
- src/lib/notion/client.ts
- src/lib/notion/request-params.ts
- src/server-constants.ts
> Get blog info from notion db

- src/lib/blog-helpers.ts
> Fix pagination link

- src/components/BlogPostsLink.astro
- src/components/BlogTagsLink.astro
- src/components/Pagination.astro
- src/components/PostRelativeLink.astro
- src/components/ReadMoreLink.astro
- src/layouts/Layout.astro
- src/pages/index.astro
- src/pages/posts/[slug].astro
- src/pages/posts/page/[page].astro
- src/pages/posts/tag/[tag].astro
- src/pages/posts/tag/[tag]/page/[page].astro
- src/styles/blog.module.css
> Rearrange layout

- astro.config.mjs
- src/integrations/cover-image-downloader.ts
- src/layouts/Layout.astro
- src/lib/notion/client.ts
> Display DB cover

- src/components/notion-blocks/annotations/Anchor.astro
- src/layouts/Layout.astro
> Change link text style

- src/layouts/Layout.astro
> Display Icon and Emoji next to site title

- src/components/PostExcerpt.astro
- src/components/PostFeaturedImage.astro
- src/components/PostTitle.astro
- src/components/notion-blocks/BulletedListItems.astro
- src/components/notion-blocks/Callout.astro
- src/components/notion-blocks/Divider.astro
- src/components/notion-blocks/File.astro
- src/components/notion-blocks/Heading1.astro
- src/components/notion-blocks/Heading2.astro
- src/components/notion-blocks/Heading3.astro
- src/components/notion-blocks/Image.astro
- src/components/notion-blocks/NumberedListItems.astro
- src/components/notion-blocks/Paragraph.astro
- src/components/notion-blocks/Quote.astro
- src/components/notion-blocks/Table.astro
- src/components/notion-blocks/TableOfContents.astro
- src/components/notion-blocks/annotations/Code.astro
- src/layouts/Layout.astro
- src/styles/blog.module.css
> Adjust styles

- src/components/notion-blocks/Code.astro
Fixes https://github.com/otoyo/astro-notion-blog/issues/104
> Re-update copied text

- src/components/notion-blocks/LinkToPage.astro
> Support Notion icon in Link to page blocks

- src/components/notion-blocks/LinkToPage.astro
- src/components/notion-blocks/Mention.astro
- src/components/notion-blocks/RichText.astro
- src/lib/interfaces.ts
- src/lib/notion/client.ts
> Support page mention

- src/components/notion-blocks/Table.astro
> Align text left in th

- src/lib/blog-helpers.ts
ref. https://github.com/otoyo/astro-notion-blog/pull/117
> Add base path to downloaded image

- src/layouts/Layout.astro
> Consider BASE_PATH

- src/components/notion-blocks/Callout.astro
> Change font-weight in callout

- src/components/notion-blocks/Code.astro
> Add pre-wrap

- src/components/notion-blocks/NumberedListItems.astro
Fixes https://github.com/otoyo/astro-notion-blog/issues/126
> Fix numbered list type

- astro.config.mjs
> Support Vercel

- src/lib/notion/client.ts
> Join post title

- src/lib/notion/client.ts
> Join RichText objects as well

- package-lock.json
- src/components/BlogPostsLink.astro
- src/components/NotionBlocks.astro
- src/components/notion-blocks/Table.astro
- src/layouts/Layout.astro
> Version 0.6.0

- src/lib/notion/client.ts
> Support external in FeaturedImage

- package-lock.json
- package.json
> Downgrade Nx

- src/components/notion-blocks/RichText.astro
> Remove spaces in annotations

- package-lock.json
- package.json
- src/lib/notion/client.ts
> Remove private info from exif

- src/components/notion-blocks/Bookmark.astro
Issue: https://suzu-hmjn.notion.site/suzu-hmjn/d6e5c91f6c554c6ab31f4490b233994d
How to fix: https://stackoverflow.com/questions/64642505/white-space-nowrap-css-style-not-allowing-for-table-to-be-responsive
> Add width and min-width to bookmark title

- package-lock.json
- package.json
- src/lib/notion/client.ts
Fixes https://github.com/otoyo/astro-notion-blog/issues/151
> Rotate by following orientation

- src/components/notion-blocks/Callout.astro
- src/lib/notion/client.ts
Fixes https://github.com/otoyo/astro-notion-blog/issues/155
> Support empty icon in callout

- src/components/notion-blocks/Mention.astro
- src/components/notion-blocks/annotations/Anchor.astro
> Fix page link style

- src/components/notion-blocks/Embed.astro
- src/components/notion-blocks/InstagramEmbed.astro
- src/components/notion-blocks/PinterestEmbed.astro
- src/components/notion-blocks/TikTokEmbed.astro
- src/components/notion-blocks/TweetEmbed.astro
- src/lib/blog-helpers.ts
Support the following social media.
* TikTok
* Instagram
* Pnterest
> Support other social media

- src/components/notion-blocks/Bookmark.astro
ref. https://github.com/otoyo/astro-notion-blog/pull/160
> Add description for Amazon

- src/components/BlogPostsLink.astro
- src/components/BlogTagsLink.astro
- src/components/PostFeaturedImage.astro
- src/components/PostTitle.astro
- src/components/notion-blocks/Bookmark.astro
- src/components/notion-blocks/Callout.astro
- src/components/notion-blocks/File.astro
- src/components/notion-blocks/Heading1.astro
- src/components/notion-blocks/Heading2.astro
- src/components/notion-blocks/Heading3.astro
- src/components/notion-blocks/Image.astro
- src/components/notion-blocks/Mention.astro
- src/layouts/Layout.astro
- src/pages/posts/page/[page].astro
- src/pages/posts/tag/[tag].astro
- src/pages/posts/tag/[tag]/page/[page].astro
- src/styles/blog.module.css
> Improve insight score

- src/components/notion-blocks/InstagramEmbed.astro
- src/components/notion-blocks/PinterestEmbed.astro
- src/components/notion-blocks/TikTokEmbed.astro
- src/components/notion-blocks/TweetEmbed.astro
> Fix url type

- package-lock.json
- package.json
- src/components/SearchButton.astro
- src/components/SearchModal.astro
- src/layouts/Layout.astro
> Add search button

- src/components/notion-blocks/CodePenEmbed.astro
> Add CodePen embed aspect-ratio

- src/lib/notion/client.ts
ref. https://github.com/otoyo/astro-notion-blog/issues/180
> Return promise in downloadFile()

- .github/workflows/format.yml
- .github/workflows/lint.yml
> Update GitHub Actions

- src/components/notion-blocks/Code.astro
- src/components/notion-blocks/File.astro
- src/components/notion-blocks/Image.astro
- src/components/notion-blocks/SyncedBlock.astro
importパスの正しくないもの、不足していたものを修正しましたので、一応PRお送りしておきます。
> importパスの誤りを修正

- package.json
> Update version 0.10.0
